services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: ./build_with_docker.sh
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambda-lint_pycodestyle
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAJTUSZCFJO2PNDFHQ
      secret_access_key:
        secure: EP8/o2FNOx4qRXPVN/Q+6AGkse56FTcwcGDIXnP+Dg/mfI68/d9ovxKmbKfFzQ9GqM/ONLcok0Q7cnvhMRb7YVEGi1uXBeKW173huhgBGDmFdkp1H0SD25Rn9tO2CrkntgICuXI0U/FauY9EbqDgF7yU+wZ1Rj14WM8QnprekF5dJ0nTvo7ehmzj2skUQlCWutuPFBu4loQc+oL7uwozX96TA4EtIQcOPdIWMrunpQTEAjThBo6pF1O6LVqLMUMBBHFqjOUFWIuHfnBElM+/P1D/DU6KX7Rn38hzshn+M66q231js3Dt9q8zxOJGGyVQ0XCbQxS53f07g0gHX+pLsST24+KPLIgCScZlcbzYk4yA4P33LoJ/pQqe8/z9Yi2+s57YssKdhwdCFdya+vCgoX1dZYZV9QxcU2NLyLVU767HE8BTmr0x2pS7O957mLFoOp7ycyoCquUxvQYUnF7lCsGTdHujoBWWfzjzZo6zUAm/Ya7xDeF699yycZAQMSfJBXdaMl9DEcmnGOQLG3zkYaClH4kmZpRTbAA4EovxC5bk9xFMtYrYKo7RCnjdShmQJG3/5Wvvys3JwL98Ce//mZvvlDZ7aZam6Klvmq34HmowjFXlJpWYuzEfOu/n6ctlaefuYGQGeNwZoJtfYJK5so905i9r/jylndAxO1abwFk=
      on:
        repo: FussyFox/pycodestyle
